on: [push]
jobs:
  Deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/app
        run: bun install
      - name: Build
        working-directory: ${{ github.workspace }}/app
        run: bun run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          # Artifact name
          name: build-output
          # Path of the directory containing the static assets.
          path: ${{ github.workspace }}/app/dist
