on: [push]
jobs:
  Deploy:
    permissions:
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/app
        run: bun install
      - name: Build
        working-directory: ${{ github.workspace }}/app
        run: bun run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: build
          path: ${{ github.workspace }}/app/dist
          if-no-files-found: error
      - uses: actions/deploy-pages@v3.0.1
        with:
          artifact-name: build
