on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ github.workspace }}/app
        run: bun install
      - name: Build
        working-directory: ${{ github.workspace }}/app
        run: bun run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/app/dist
          if-no-files-found: error
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy artifact to pages.
        uses: actions/deploy-pages@v3
